runtime: nodejs18
service: frontend
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6
handlers:
- url: /(.*\.(json|ico|js|css))$
  static_files: build/\1
  upload: build/.*\.(json|ico|js|css)$
- url: /static
  static_dir: build/static
- url: /.*
  static_files: build/index.html
  upload: build/index.html
